spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sparta-next-me/project-configs
          default-label: main
          search-paths:
            - configs/common
            - configs/{application}/{profile}
            - configs/{application}
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # [수정] 외부 IP 대신 쿠버네티스 내부 Service DNS 주소 사용
      defaultZone: http://eureka-server.next-me.svc.cluster.local:3151/eureka/
