spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sparta-next-me/project-configs
          default-label: main
          search-paths:
            - configs/common
            - configs/{application}/{profile}
            - configs/{application}
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # k8s 내부에서는 Service DNS 사용
      defaultZone: http://34.50.7.8:3150/eureka/
